# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA.xci
# IP: The module: 'Fifo_Auto_TA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA.xci
# IP: The module: 'Fifo_Auto_TA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Work_File/CEPC/Logic/DIF-Logic/ECAL_DIF/ECAL_DIF.srcs/sources_1/ip/Fifo_Auto_TA/Fifo_Auto_TA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Auto_TA'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
