create_clock -period 12.500 -name Clk_In -waveform {0.000 6.250} [get_ports Clk_In]
set_input_delay -clock [get_clocks Clk_In] -min -add_delay 6.000 [get_ports Rst_n]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#config SPI Flash
#set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]


#Pin location constrains
set_property PACKAGE_PIN U20 [get_ports Clk_In]
set_property IOSTANDARD LVCMOS33 [get_ports Clk_In]
set_property IOSTANDARD LVCMOS33 [get_ports Rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Faddr[0]}]
set_property PACKAGE_PIN V18 [get_ports {Usb_Faddr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Faddr[1]}]
set_property PACKAGE_PIN AA21 [get_ports {Usb_Faddr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[0]}]
set_property PACKAGE_PIN W22 [get_ports {Usb_Fdata[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Usb_Fdata[15]}]
set_property PACKAGE_PIN T21 [get_ports {Usb_Fdata[1]}]
set_property PACKAGE_PIN R17 [get_ports {Usb_Fdata[2]}]
set_property PACKAGE_PIN T18 [get_ports {Usb_Fdata[4]}]
set_property PACKAGE_PIN R18 [get_ports {Usb_Fdata[5]}]
set_property PACKAGE_PIN U21 [get_ports {Usb_Fdata[6]}]
set_property PACKAGE_PIN U18 [get_ports {Usb_Fdata[7]}]
set_property PACKAGE_PIN AB20 [get_ports {Usb_Fdata[8]}]
set_property PACKAGE_PIN AA19 [get_ports {Usb_Fdata[9]}]
set_property PACKAGE_PIN AA18 [get_ports {Usb_Fdata[10]}]
set_property PACKAGE_PIN AB18 [get_ports {Usb_Fdata[11]}]
set_property PACKAGE_PIN V17 [get_ports {Usb_Fdata[12]}]
set_property PACKAGE_PIN W17 [get_ports {Usb_Fdata[13]}]
set_property PACKAGE_PIN U17 [get_ports {Usb_Fdata[14]}]
set_property PACKAGE_PIN R16 [get_ports {Usb_Fdata[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Flaga]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Flagb]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Flagc]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Flagd]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Ifclk]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Pktend]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Sloe]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Slrd]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Slwr]
set_property IOSTANDARD LVCMOS33 [get_ports Usb_Wu]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Ck40_Test]
set_property PACKAGE_PIN R3 [get_ports Out_Ck40_Test]
set_property IOSTANDARD LVCMOS25 [get_ports In_Chipsatb]
set_property IOSTANDARD LVCMOS25 [get_ports In_Digital_Prob1]
set_property IOSTANDARD LVCMOS25 [get_ports In_Digital_Prob2]
set_property IOSTANDARD LVCMOS25 [get_ports In_Dout_1b]
set_property IOSTANDARD LVCMOS25 [get_ports In_Dout_2b]
set_property IOSTANDARD LVCMOS25 [get_ports In_End_Readout1]
set_property IOSTANDARD LVCMOS25 [get_ports In_End_Readout2]
set_property IOSTANDARD LVCMOS25 [get_ports In_Sr_Out]
set_property IOSTANDARD LVCMOS25 [get_ports In_Srout_Read]
set_property IOSTANDARD LVCMOS25 [get_ports In_TransmitOn_1B]
set_property IOSTANDARD LVCMOS25 [get_ports In_TransmitOn_2B]
set_property IOSTANDARD LVCMOS25 [get_ports In_Trig_Outb]
set_property IOSTANDARD LVDS_25 [get_ports Out_Ck_5P]
set_property IOSTANDARD LVDS_25 [get_ports Out_Ck_5N]
set_property IOSTANDARD LVDS_25 [get_ports Out_Ck_40P]
set_property IOSTANDARD LVDS_25 [get_ports Out_Ck_40N]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Ck_Read]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Control_ADG]
set_property IOSTANDARD LVCMOS33 [get_ports Out_CS_n_Cali]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Din_Cali]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Hold]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Pwr_On_A]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Pwr_On_D]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Pwr_On_Adc]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Pwr_On_Dac]
set_property IOSTANDARD LVDS_25 [get_ports Out_Raz_Chn_P]
set_property IOSTANDARD LVDS_25 [get_ports Out_Raz_Chn_N]
set_property IOSTANDARD LVDS_25 [get_ports Out_Trig_Ext_N]
set_property IOSTANDARD LVDS_25 [get_ports Out_Val_Evt_P]
set_property IOSTANDARD LVDS_25 [get_ports Out_Val_Evt_N]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Resetb]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Rstb_Pa]
set_property IOSTANDARD LVCMOS33 [get_ports Out_SCLK_Cali]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Select]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Sr_Ck]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Sr_In]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Sr_Rstb]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Srin_Read]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Acq]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Convb]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Ramp_TDC_Ext]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Rampb_ADC_Ext]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Readout1]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Start_Readout2]
set_property IOSTANDARD LVDS_25 [get_ports Out_Trig_Ext_P]
set_property IOSTANDARD LVCMOS33 [get_ports SMA_ExTrig_Cnt]
set_property PACKAGE_PIN P16 [get_ports {Usb_Fdata[3]}]


set_property IOSTANDARD LVCMOS25 [get_ports SMA4]
set_property IOSTANDARD LVCMOS25 [get_ports SMA5]
set_property IOSTANDARD LVCMOS33 [get_ports SMA3]
set_property IOSTANDARD LVCMOS33 [get_ports SMA1]
set_property IOSTANDARD LVCMOS33 [get_ports SMA2]

set_property PACKAGE_PIN A20 [get_ports {LED[1]}]
set_property PACKAGE_PIN C22 [get_ports {LED[2]}]
set_property PACKAGE_PIN E22 [get_ports {LED[5]}]
set_property PACKAGE_PIN E21 [get_ports {LED[4]}]
set_property PACKAGE_PIN D21 [get_ports {LED[3]}]
set_property PACKAGE_PIN G22 [get_ports {LED[8]}]
set_property PACKAGE_PIN G21 [get_ports {LED[7]}]
set_property PACKAGE_PIN F20 [get_ports {LED[6]}]
set_property PACKAGE_PIN H2 [get_ports Out_Val_Evt_P]
set_property PACKAGE_PIN M1 [get_ports Out_Trig_Ext_P]
set_property PACKAGE_PIN K1 [get_ports Out_Ck_40P]
set_property PACKAGE_PIN R1 [get_ports Out_Raz_Chn_P]
set_property PACKAGE_PIN AA20 [get_ports Usb_Wu]
set_property PACKAGE_PIN W19 [get_ports Usb_Slwr]
set_property PACKAGE_PIN AB22 [get_ports Usb_Slrd]
set_property PACKAGE_PIN Y21 [get_ports Usb_Sloe]
set_property PACKAGE_PIN AB21 [get_ports Usb_Pktend]
set_property PACKAGE_PIN Y22 [get_ports Usb_Ifclk]
set_property PACKAGE_PIN Y19 [get_ports Usb_Flagd]
set_property PACKAGE_PIN W21 [get_ports Usb_Flagc]
set_property PACKAGE_PIN W20 [get_ports Usb_Flagb]
set_property PACKAGE_PIN V20 [get_ports Usb_Flaga]
set_property PACKAGE_PIN G15 [get_ports SMA5]
set_property PACKAGE_PIN G13 [get_ports SMA4]
set_property PACKAGE_PIN B15 [get_ports SMA3]
set_property PACKAGE_PIN A21 [get_ports SMA2]
set_property PACKAGE_PIN B21 [get_ports SMA1]
set_property PACKAGE_PIN D19 [get_ports Rst_n]
set_property PACKAGE_PIN T3 [get_ports Out_Start_Readout2]
set_property PACKAGE_PIN U1 [get_ports Out_Start_Readout1]
set_property PACKAGE_PIN R4 [get_ports Out_Start_Rampb_ADC_Ext]
set_property PACKAGE_PIN T1 [get_ports Out_Start_Ramp_TDC_Ext]
set_property PACKAGE_PIN T4 [get_ports Out_Start_Convb]
set_property PACKAGE_PIN R2 [get_ports Out_Start_Acq]
set_property PACKAGE_PIN V2 [get_ports Out_Sr_Rstb]
set_property PACKAGE_PIN V4 [get_ports Out_Sr_In]
set_property PACKAGE_PIN W1 [get_ports Out_Sr_Ck]
set_property PACKAGE_PIN V3 [get_ports Out_Select]
set_property PACKAGE_PIN AB2 [get_ports Out_SCLK_Cali]
set_property PACKAGE_PIN W5 [get_ports Out_Rstb_Pa]
set_property PACKAGE_PIN U3 [get_ports Out_Resetb]
set_property PACKAGE_PIN AB1 [get_ports Out_Pwr_On_Dac]
set_property PACKAGE_PIN W2 [get_ports Out_Pwr_On_D]
set_property PACKAGE_PIN AA1 [get_ports Out_Pwr_On_Adc]
set_property PACKAGE_PIN W4 [get_ports Out_Pwr_On_A]
set_property PACKAGE_PIN Y1 [get_ports Out_Hold]
set_property PACKAGE_PIN AA3 [get_ports Out_Din_Cali]
set_property PACKAGE_PIN Y2 [get_ports Out_CS_n_Cali]
set_property PACKAGE_PIN U5 [get_ports Out_Control_ADG]
set_property PACKAGE_PIN W6 [get_ports Out_Ck_Read]
set_property PACKAGE_PIN Y4 [get_ports Out_Srin_Read]
set_property PACKAGE_PIN P2 [get_ports In_Trig_Outb]
set_property PACKAGE_PIN K2 [get_ports In_TransmitOn_2B]
set_property PACKAGE_PIN K3 [get_ports In_TransmitOn_1B]
set_property PACKAGE_PIN B2 [get_ports In_Srout_Read]
set_property PACKAGE_PIN G3 [get_ports In_Sr_Out]
set_property PACKAGE_PIN M3 [get_ports In_End_Readout2]
set_property PACKAGE_PIN K4 [get_ports In_End_Readout1]
set_property PACKAGE_PIN N2 [get_ports In_Dout_2b]
set_property PACKAGE_PIN M2 [get_ports In_Dout_1b]
set_property PACKAGE_PIN B1 [get_ports In_Digital_Prob2]
set_property PACKAGE_PIN A1 [get_ports In_Digital_Prob1]
set_property PACKAGE_PIN D1 [get_ports In_Chipsatb]
set_property PACKAGE_PIN G1 [get_ports Out_Ck_5P]
set_property PACKAGE_PIN A13 [get_ports SMA_ExTrig_Cnt]
set_property IOSTANDARD LVCMOS33 [get_ports In_Hv_Tx]
set_property IOSTANDARD LVCMOS33 [get_ports Out_Hv_Rx]
set_property PACKAGE_PIN AA4 [get_ports Out_Hv_Rx]
set_property PACKAGE_PIN AB3 [get_ports In_Hv_Tx]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list Clk_Out_2_All]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 56 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {Debug_Sig_Sig_7byte_Hv[1]} {Debug_Sig_Sig_7byte_Hv[2]} {Debug_Sig_Sig_7byte_Hv[3]} {Debug_Sig_Sig_7byte_Hv[4]} {Debug_Sig_Sig_7byte_Hv[5]} {Debug_Sig_Sig_7byte_Hv[6]} {Debug_Sig_Sig_7byte_Hv[7]} {Debug_Sig_Sig_7byte_Hv[8]} {Debug_Sig_Sig_7byte_Hv[9]} {Debug_Sig_Sig_7byte_Hv[10]} {Debug_Sig_Sig_7byte_Hv[11]} {Debug_Sig_Sig_7byte_Hv[12]} {Debug_Sig_Sig_7byte_Hv[13]} {Debug_Sig_Sig_7byte_Hv[14]} {Debug_Sig_Sig_7byte_Hv[15]} {Debug_Sig_Sig_7byte_Hv[16]} {Debug_Sig_Sig_7byte_Hv[17]} {Debug_Sig_Sig_7byte_Hv[18]} {Debug_Sig_Sig_7byte_Hv[19]} {Debug_Sig_Sig_7byte_Hv[20]} {Debug_Sig_Sig_7byte_Hv[21]} {Debug_Sig_Sig_7byte_Hv[22]} {Debug_Sig_Sig_7byte_Hv[23]} {Debug_Sig_Sig_7byte_Hv[24]} {Debug_Sig_Sig_7byte_Hv[25]} {Debug_Sig_Sig_7byte_Hv[26]} {Debug_Sig_Sig_7byte_Hv[27]} {Debug_Sig_Sig_7byte_Hv[28]} {Debug_Sig_Sig_7byte_Hv[29]} {Debug_Sig_Sig_7byte_Hv[30]} {Debug_Sig_Sig_7byte_Hv[31]} {Debug_Sig_Sig_7byte_Hv[32]} {Debug_Sig_Sig_7byte_Hv[33]} {Debug_Sig_Sig_7byte_Hv[34]} {Debug_Sig_Sig_7byte_Hv[35]} {Debug_Sig_Sig_7byte_Hv[36]} {Debug_Sig_Sig_7byte_Hv[37]} {Debug_Sig_Sig_7byte_Hv[38]} {Debug_Sig_Sig_7byte_Hv[39]} {Debug_Sig_Sig_7byte_Hv[40]} {Debug_Sig_Sig_7byte_Hv[41]} {Debug_Sig_Sig_7byte_Hv[42]} {Debug_Sig_Sig_7byte_Hv[43]} {Debug_Sig_Sig_7byte_Hv[44]} {Debug_Sig_Sig_7byte_Hv[45]} {Debug_Sig_Sig_7byte_Hv[46]} {Debug_Sig_Sig_7byte_Hv[47]} {Debug_Sig_Sig_7byte_Hv[48]} {Debug_Sig_Sig_7byte_Hv[49]} {Debug_Sig_Sig_7byte_Hv[50]} {Debug_Sig_Sig_7byte_Hv[51]} {Debug_Sig_Sig_7byte_Hv[52]} {Debug_Sig_Sig_7byte_Hv[53]} {Debug_Sig_Sig_7byte_Hv[54]} {Debug_Sig_Sig_7byte_Hv[55]} {Debug_Sig_Sig_7byte_Hv[56]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Debug_Sig_Sig_In_Hv_Control_Word[1]} {Debug_Sig_Sig_In_Hv_Control_Word[2]} {Debug_Sig_Sig_In_Hv_Control_Word[3]} {Debug_Sig_Sig_In_Hv_Control_Word[4]} {Debug_Sig_Sig_In_Hv_Control_Word[5]} {Debug_Sig_Sig_In_Hv_Control_Word[6]} {Debug_Sig_Sig_In_Hv_Control_Word[7]} {Debug_Sig_Sig_In_Hv_Control_Word[8]} {Debug_Sig_Sig_In_Hv_Control_Word[9]} {Debug_Sig_Sig_In_Hv_Control_Word[10]} {Debug_Sig_Sig_In_Hv_Control_Word[11]} {Debug_Sig_Sig_In_Hv_Control_Word[12]} {Debug_Sig_Sig_In_Hv_Control_Word[13]} {Debug_Sig_Sig_In_Hv_Control_Word[14]} {Debug_Sig_Sig_In_Hv_Control_Word[15]} {Debug_Sig_Sig_In_Hv_Control_Word[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {Debug_Sig_Sig_Mask_Word[1]} {Debug_Sig_Sig_Mask_Word[2]} {Debug_Sig_Sig_Mask_Word[3]} {Debug_Sig_Sig_Mask_Word[4]} {Debug_Sig_Sig_Mask_Word[5]} {Debug_Sig_Sig_Mask_Word[6]} {Debug_Sig_Sig_Mask_Word[7]} {Debug_Sig_Sig_Mask_Word[8]} {Debug_Sig_Sig_Mask_Word[9]} {Debug_Sig_Sig_Mask_Word[10]} {Debug_Sig_Sig_Mask_Word[11]} {Debug_Sig_Sig_Mask_Word[12]} {Debug_Sig_Sig_Mask_Word[13]} {Debug_Sig_Sig_Mask_Word[14]} {Debug_Sig_Sig_Mask_Word[15]} {Debug_Sig_Sig_Mask_Word[16]} {Debug_Sig_Sig_Mask_Word[17]} {Debug_Sig_Sig_Mask_Word[18]} {Debug_Sig_Sig_Mask_Word[19]} {Debug_Sig_Sig_Mask_Word[20]} {Debug_Sig_Sig_Mask_Word[21]} {Debug_Sig_Sig_Mask_Word[22]} {Debug_Sig_Sig_Mask_Word[23]} {Debug_Sig_Sig_Mask_Word[24]} {Debug_Sig_Sig_Mask_Word[25]} {Debug_Sig_Sig_Mask_Word[26]} {Debug_Sig_Sig_Mask_Word[27]} {Debug_Sig_Sig_Mask_Word[28]} {Debug_Sig_Sig_Mask_Word[29]} {Debug_Sig_Sig_Mask_Word[30]} {Debug_Sig_Sig_Mask_Word[31]} {Debug_Sig_Sig_Mask_Word[32]} {Debug_Sig_Sig_Mask_Word[33]} {Debug_Sig_Sig_Mask_Word[34]} {Debug_Sig_Sig_Mask_Word[35]} {Debug_Sig_Sig_Mask_Word[36]} {Debug_Sig_Sig_Mask_Word[37]} {Debug_Sig_Sig_Mask_Word[38]} {Debug_Sig_Sig_Mask_Word[39]} {Debug_Sig_Sig_Mask_Word[40]} {Debug_Sig_Sig_Mask_Word[41]} {Debug_Sig_Sig_Mask_Word[42]} {Debug_Sig_Sig_Mask_Word[43]} {Debug_Sig_Sig_Mask_Word[44]} {Debug_Sig_Sig_Mask_Word[45]} {Debug_Sig_Sig_Mask_Word[46]} {Debug_Sig_Sig_Mask_Word[47]} {Debug_Sig_Sig_Mask_Word[48]} {Debug_Sig_Sig_Mask_Word[49]} {Debug_Sig_Sig_Mask_Word[50]} {Debug_Sig_Sig_Mask_Word[51]} {Debug_Sig_Sig_Mask_Word[52]} {Debug_Sig_Sig_Mask_Word[53]} {Debug_Sig_Sig_Mask_Word[54]} {Debug_Sig_Sig_Mask_Word[55]} {Debug_Sig_Sig_Mask_Word[56]} {Debug_Sig_Sig_Mask_Word[57]} {Debug_Sig_Sig_Mask_Word[58]} {Debug_Sig_Sig_Mask_Word[59]} {Debug_Sig_Sig_Mask_Word[60]} {Debug_Sig_Sig_Mask_Word[61]} {Debug_Sig_Sig_Mask_Word[62]} {Debug_Sig_Sig_Mask_Word[63]} {Debug_Sig_Sig_Mask_Word[64]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[1]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[2]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[3]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[4]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[5]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[6]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[7]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[8]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[9]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[10]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[11]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[12]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[13]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[14]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[15]} {Debug_Sig_Sig_Parallel_Data_From_Auto_Scan_Temp[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list Debug_Sig_Out_Hv_Rx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list Debug_Sig_Sig_Flag_Start_Stop_Hv]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list Debug_Sig_Sig_In_Hv_Control_En]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list Debug_Sig_Sig_Select_Start_SC]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list Debug_Sig_Sig_Start_SC]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list Debug_Sig_Sig_Start_Stop_Hv]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets Clk_Out_2_All]
